services:
  - type: web
    name: mystery-loot-box
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: build,runtime
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        scope: runtime
      - key: STRIPE_SECRET_KEY
        scope: runtime
      - key: STRIPE_PUBLISHABLE_KEY
        scope: runtime
      - key: MAILJET_API_KEY
        scope: runtime
      - key: MAILJET_API_SECRET
        scope: runtime
      - key: MAILJET_SENDER_EMAIL
        scope: runtime
      - key: MAILJET_SENDER_NAME
        value: Lucky Box
      - key: FRONTEND_BASE_URL
        value: (your-render-url)
      - key: BACKEND_BASE_URL
        value: (your-render-url)
